[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
base = "light"
primaryColor = "#d97834"
backgroundColor = "#c5ced6"
secondaryBackgroundColor = "#ffffff"
textColor = "#141a22"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
